/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;
import Execoes.*;
import Utilizadores.Admin;
import Utilizadores.Cliente;
import Utilizadores.Utilizador;
import trabPrat.*;
import UI.EcraInicial.*;


/**
 *
 * @author jcarl
 */
public class Login extends javax.swing.JPanel {
    
    private EcraInicial frame;
    
    private String user,password;
    
    private Utilizador util;

    /**
     * Creates new form Login
     */
    public Login(EcraInicial frame) {
        initComponents();
        this.frame = frame;
        this.jLabelContaNaoReconhecida.setVisible(false);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {


  	  jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldUserName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
	  jPanel1 = new javax.swing.JPanel();
        jTextFieldPassword = new javax.swing.JTextField();
        jLabelContaNaoReconhecida = new javax.swing.JLabel();
        jButtonRetroceder = new javax.swing.JButton();
        jButtonEntrar = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 255, 153));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Bem Vindo");

        jLabel4.setText("User Name:");

        jLabel5.setText("Password:");

        jLabelContaNaoReconhecida.setText("Conta não reconhecida");

        jButtonRetroceder.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonRetroceder.setText("Voltar");
        jButtonRetroceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetrocederActionPerformed(evt);
            }
        });

        jButtonEntrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonEntrar.setText("Entrar");
        jButtonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntrarActionPerformed(evt);
            }
        });


        setMinimumSize(new java.awt.Dimension(640, 360));

        jPanel1.setBackground(new java.awt.Color(12, 45, 72));
        jPanel1.setMaximumSize(new java.awt.Dimension(640, 360));
        jPanel1.setMinimumSize(new java.awt.Dimension(640, 360));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

     
        
   

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents




     private void jButtonRetrocederActionPerformed(java.awt.event.ActionEvent evt){
       this.frame.retrocederPainel();   
    }

    private void jButtonEntrarActionPerformed(java.awt.event.ActionEvent evt) {                                         
       this.user = this.jTextFieldUserName.getText() ;
       this.password = this.jTextFieldPassword.getText();
  
       try {
           util = criarUsers.getInstance().loginSistema(this.user, this.password) ;
       } catch (ContaNaoReconhecida e) {
           this.jLabelContaNaoReconhecida.setVisible(true);
       }
       if (util instanceof Admin) {
           Admin admin = (Admin) util ;
           MenuAdmin pAdmin = new MenuAdmin (this.frame, admin);
           this.frame.avançarPainel(pAdmin , this);
       }
       if (util instanceof Cliente) {
           Cliente cliente = (Cliente) util ;
           MenuUser cliente1 = new MenuUser (this.frame , cliente);
           this.frame.avançarParaPainel(cliente1, this);
       }
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
  
    private javax.swing.JLabel jLabel2;

    private javax.swing.JLabel jLabel3;

    private javax.swing.JPanel jPanel1;

    private javax.swing.JTextField jTextFieldUserName;
    private javax.swing.JTextField jTextFieldPassword;

    private javax.swing.JButton jButtonEntrar;
    private javax.swing.JButton jButtonRetroceder;


    private javax.swing.JLabel jLabel4;

    private javax.swing.JLabel jLabel5;

    private javax.swing.JLabel jLabelContaNaoReconhecida;
   
    // End of variables declaration//GEN-END:variables


}
