/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import BLL.BLLMenuAdmin;
import BLL.dados;
import DAL.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jcarl
 */
public class MenuAdmin extends javax.swing.JFrame {
    dados d = new dados();
    BLLMenuAdmin a = new BLLMenuAdmin();
    /**
     * Creates new form MenuAdmin
     */
    public MenuAdmin(Utilizador admin) {
        initComponents();
        TrocarMenu(1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        addAdminPanel = new javax.swing.JPanel();
        registoadmin_email_input = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        registoadmin_password_input = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        errorRegistoAdmin = new javax.swing.JLabel();
        addDonoPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        registo_email_input = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        registo_password_input = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        registo_nome_input = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        registo_telemovel_input = new javax.swing.JTextField();
        errorRegistoDono = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        UsersPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        usersTable = new javax.swing.JTable();
        deleteUser = new javax.swing.JButton();
        DonosPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        donosTable = new javax.swing.JTable();
        addDono = new javax.swing.JButton();
        deleteDono = new javax.swing.JButton();
        AdminsPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        adminTable = new javax.swing.JTable();
        addAdmin = new javax.swing.JButton();
        deleteAdmin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1366, 745));
        setMinimumSize(new java.awt.Dimension(1366, 745));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(127, 109, 82));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(127, 109, 82));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Logout");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 0, 185, 70));

        jButton2.setBackground(new java.awt.Color(127, 109, 82));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Gerir Users");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 198, 70));

        jButton3.setBackground(new java.awt.Color(127, 109, 82));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Gerir Donos");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 185, 70));

        jButton4.setBackground(new java.awt.Color(127, 109, 82));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Gerir Admins");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 185, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 70));

        jLayeredPane1.setBackground(new java.awt.Color(146, 129, 102));

        addAdminPanel.setBackground(new java.awt.Color(146, 129, 102));
        addAdminPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registoadmin_email_input.setBackground(new java.awt.Color(255, 255, 255));
        registoadmin_email_input.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        registoadmin_email_input.setForeground(new java.awt.Color(0, 0, 0));
        registoadmin_email_input.setBorder(null);
        registoadmin_email_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registoadmin_email_inputActionPerformed(evt);
            }
        });
        addAdminPanel.add(registoadmin_email_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 470, 40));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Email");
        addAdminPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 120, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Adicionar Dono Stand");
        addAdminPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 1280, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Password:");
        addAdminPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 90, -1));

        registoadmin_password_input.setBackground(new java.awt.Color(255, 255, 255));
        registoadmin_password_input.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        registoadmin_password_input.setForeground(new java.awt.Color(0, 0, 0));
        registoadmin_password_input.setBorder(null);
        registoadmin_password_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registoadmin_password_inputActionPerformed(evt);
            }
        });
        addAdminPanel.add(registoadmin_password_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, 470, 40));

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 0, 0));
        jButton6.setText("Adicionar Admin");
        jButton6.setBorder(null);
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton6MousePressed(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        addAdminPanel.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 410, 260, 50));

        errorRegistoAdmin.setBackground(new java.awt.Color(255, 0, 51));
        errorRegistoAdmin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        errorRegistoAdmin.setForeground(new java.awt.Color(153, 0, 0));
        errorRegistoAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorRegistoAdmin.setText("Erro Registo");
        addAdminPanel.add(errorRegistoAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 370, 300, 20));

        addDonoPanel.setBackground(new java.awt.Color(146, 129, 102));
        addDonoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Adicionar Dono Stand");
        addDonoPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 1280, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Email");
        addDonoPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 120, -1));

        registo_email_input.setBackground(new java.awt.Color(255, 255, 255));
        registo_email_input.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        registo_email_input.setForeground(new java.awt.Color(0, 0, 0));
        registo_email_input.setBorder(null);
        registo_email_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registo_email_inputActionPerformed(evt);
            }
        });
        addDonoPanel.add(registo_email_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 470, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Password:");
        addDonoPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 90, -1));

        registo_password_input.setBackground(new java.awt.Color(255, 255, 255));
        registo_password_input.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        registo_password_input.setForeground(new java.awt.Color(0, 0, 0));
        registo_password_input.setBorder(null);
        registo_password_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registo_password_inputActionPerformed(evt);
            }
        });
        addDonoPanel.add(registo_password_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 470, 40));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nome:");
        addDonoPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, 90, -1));

        registo_nome_input.setBackground(new java.awt.Color(255, 255, 255));
        registo_nome_input.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        registo_nome_input.setForeground(new java.awt.Color(0, 0, 0));
        registo_nome_input.setBorder(null);
        registo_nome_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registo_nome_inputActionPerformed(evt);
            }
        });
        addDonoPanel.add(registo_nome_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 470, 40));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Telemovel:");
        addDonoPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, 100, -1));

        registo_telemovel_input.setBackground(new java.awt.Color(255, 255, 255));
        registo_telemovel_input.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        registo_telemovel_input.setForeground(new java.awt.Color(0, 0, 0));
        registo_telemovel_input.setBorder(null);
        registo_telemovel_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registo_telemovel_inputActionPerformed(evt);
            }
        });
        addDonoPanel.add(registo_telemovel_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 430, 470, 40));

        errorRegistoDono.setBackground(new java.awt.Color(255, 0, 51));
        errorRegistoDono.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        errorRegistoDono.setForeground(new java.awt.Color(153, 0, 0));
        errorRegistoDono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorRegistoDono.setText("Erro Registo");
        addDonoPanel.add(errorRegistoDono, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 490, 300, 20));

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 0));
        jButton5.setText("Adicionar Dono");
        jButton5.setBorder(null);
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton5MousePressed(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        addDonoPanel.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 530, 260, 50));

        UsersPanel.setBackground(new java.awt.Color(146, 129, 102));
        UsersPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Email", "Password", "Nome", "Telemovel"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(usersTable);

        UsersPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 1250, 540));

        deleteUser.setBackground(new java.awt.Color(153, 0, 0));
        deleteUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deleteUser.setForeground(new java.awt.Color(255, 255, 255));
        deleteUser.setText("Remover");
        deleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteUserActionPerformed(evt);
            }
        });
        UsersPanel.add(deleteUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 590, 180, 40));

        DonosPanel.setBackground(new java.awt.Color(146, 129, 102));
        DonosPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        donosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Email", "Password", "Nome", "Telemovel"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(donosTable);

        DonosPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 1250, 540));

        addDono.setBackground(new java.awt.Color(51, 153, 0));
        addDono.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addDono.setForeground(new java.awt.Color(255, 255, 255));
        addDono.setText("Adicionar");
        addDono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDonoActionPerformed(evt);
            }
        });
        DonosPanel.add(addDono, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 590, 180, 40));

        deleteDono.setBackground(new java.awt.Color(153, 0, 0));
        deleteDono.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deleteDono.setForeground(new java.awt.Color(255, 255, 255));
        deleteDono.setText("Remover");
        deleteDono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteDonoActionPerformed(evt);
            }
        });
        DonosPanel.add(deleteDono, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 590, 180, 40));

        AdminsPanel.setBackground(new java.awt.Color(146, 129, 102));
        AdminsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adminTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Email", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(adminTable);

        AdminsPanel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 1250, 540));

        addAdmin.setBackground(new java.awt.Color(51, 153, 0));
        addAdmin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addAdmin.setForeground(new java.awt.Color(255, 255, 255));
        addAdmin.setText("Adicionar");
        addAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAdminActionPerformed(evt);
            }
        });
        AdminsPanel.add(addAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 590, 180, 40));

        deleteAdmin.setBackground(new java.awt.Color(153, 0, 0));
        deleteAdmin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deleteAdmin.setForeground(new java.awt.Color(255, 255, 255));
        deleteAdmin.setText("Remover");
        deleteAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAdminActionPerformed(evt);
            }
        });
        AdminsPanel.add(deleteAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 590, 180, 40));

        jLayeredPane1.setLayer(addAdminPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(addDonoPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(UsersPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(DonosPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(AdminsPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UsersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1370, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(DonosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(AdminsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(addDonoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(addAdminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1370, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UsersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(DonosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(AdminsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(addDonoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(addAdminPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE))
        );

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1370, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        TrocarMenu(1);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        TrocarMenu(2);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        TrocarMenu(3);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void deleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteUserActionPerformed
        if(usersTable.getSelectedRow() != -1){
            int resposta = JOptionPane.showConfirmDialog(this, "De certeza que pretende remover este utilizador?", "Confirmar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if(resposta == JOptionPane.YES_OPTION) {
                String id = (String) usersTable.getValueAt(usersTable.getSelectedRow(), 0);
                boolean resultado = d.removeUser(id);
                    if (resultado=true) {
                    JOptionPane.showMessageDialog(this, "Utilizador removido com sucesso!!");
                    TrocarMenu(1);
                }
            }
              
        }else{
           JOptionPane.showMessageDialog(this, "Selecione um Utilizador primeiro!!");
        }   
    }//GEN-LAST:event_deleteUserActionPerformed

    private void deleteDonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteDonoActionPerformed
        if(donosTable.getSelectedRow() != -1){
            int resposta = JOptionPane.showConfirmDialog(this, "De certeza que pretende remover este Dono?", "Confirmar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if(resposta == JOptionPane.YES_OPTION) {
                String id = (String) donosTable.getValueAt(donosTable.getSelectedRow(), 0);
                boolean resultado = d.removeUser(id);
                    if (resultado=true) {
                    JOptionPane.showMessageDialog(this, "Dono removido com sucesso!!");
                    TrocarMenu(2);
                }
            }
              
        }else{
           JOptionPane.showMessageDialog(this, "Selecione um Dono primeiro!!");
        }
    }//GEN-LAST:event_deleteDonoActionPerformed

    private void deleteAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAdminActionPerformed
        if(adminTable.getSelectedRow() != -1){
            int resposta = JOptionPane.showConfirmDialog(this, "De certeza que pretende remover este Admin?", "Confirmar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if(resposta == JOptionPane.YES_OPTION) {
                String id = (String) adminTable.getValueAt(adminTable.getSelectedRow(), 0);
                boolean resultado = d.removeUser(id);
                    if (resultado=true) {
                    JOptionPane.showMessageDialog(this, "Admin removido com sucesso!!");
                    TrocarMenu(3);
                }
            }
              
        }else{
           JOptionPane.showMessageDialog(this, "Selecione um Admin primeiro!!");
        }
    }//GEN-LAST:event_deleteAdminActionPerformed

    private void addDonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDonoActionPerformed
        TrocarMenu(4);
    }//GEN-LAST:event_addDonoActionPerformed

    private void addAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAdminActionPerformed
        TrocarMenu(5);
    }//GEN-LAST:event_addAdminActionPerformed

    private void registo_email_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registo_email_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registo_email_inputActionPerformed

    private void registo_password_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registo_password_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registo_password_inputActionPerformed

    private void registo_nome_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registo_nome_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registo_nome_inputActionPerformed

    private void registo_telemovel_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registo_telemovel_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registo_telemovel_inputActionPerformed

    private void jButton5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MousePressed

        if(this.registo_email_input.getText().isEmpty() || this.registo_password_input.getText().isEmpty()|| this.registo_nome_input.getText().isEmpty()|| this.registo_telemovel_input.getText().isEmpty()){
            this.errorRegistoDono.setText("Existem campos por preencher");
            this.errorRegistoDono.setVisible(true);
        }else{
            String email = this.registo_email_input.getText();
            String password = this.registo_password_input.getText();
            String nome = this.registo_nome_input.getText();
            String telemovel = this.registo_telemovel_input.getText();

            int status = a.addDono(email, password, nome, telemovel);
            //System.out.println(status);

            switch (status) {
                case 1:
                this.errorRegistoDono.setText("Email já em uso!");
                this.errorRegistoDono.setVisible(true);
                break;
                case 2:this.errorRegistoDono.setText("Email Inválido!");
                this.errorRegistoDono.setVisible(true);
                break;
                case 3:
                this.errorRegistoDono.setText("Numero de Telemovel Inválido!");
                this.errorRegistoDono.setVisible(true);
                break;
                case 0:
                TrocarMenu(2);
                break;
                default:
                throw new AssertionError();
            }
        }
    }//GEN-LAST:event_jButton5MousePressed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(this.registo_email_input.getText().isEmpty() || this.registo_password_input.getText().isEmpty()|| this.registo_nome_input.getText().isEmpty()|| this.registo_telemovel_input.getText().isEmpty()){
            this.errorRegistoDono.setText("Existem campos por preencher");
            this.errorRegistoDono.setVisible(true);
        }else{
            String email = this.registo_email_input.getText();
            String password = this.registo_password_input.getText();
            String nome = this.registo_nome_input.getText();
            String telemovel = this.registo_telemovel_input.getText();

            int status = a.addDono(email, password, nome, telemovel);
            //System.out.println(status);
            
            switch (status) {
                case 1:
                    this.errorRegistoDono.setText("Email já em uso!");
                    this.errorRegistoDono.setVisible(true);
                    break;
                case 2:this.errorRegistoDono.setText("Email Inválido!");
                    this.errorRegistoDono.setVisible(true);
                    break;
                case 3:
                    this.errorRegistoDono.setText("Numero de Telemovel Inválido!");
                    this.errorRegistoDono.setVisible(true);
                    break;
                case 0:
                    TrocarMenu(1);
                    break;
                default:
                    throw new AssertionError();
        }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void registoadmin_email_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registoadmin_email_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registoadmin_email_inputActionPerformed

    private void registoadmin_password_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registoadmin_password_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registoadmin_password_inputActionPerformed

    private void jButton6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6MousePressed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if(this.registoadmin_email_input.getText().isEmpty() || this.registoadmin_password_input.getText().isEmpty()){
            this.errorRegistoAdmin.setText("Existem campos por preencher");
            this.errorRegistoAdmin.setVisible(true);
        }else{
            String email = this.registoadmin_email_input.getText();
            String password = this.registoadmin_password_input.getText();

            int status = a.addAdmin(email, password);
            //System.out.println(status);
            
            switch (status) {
                case 1:
                    this.errorRegistoDono.setText("Email já em uso!");
                    this.errorRegistoDono.setVisible(true);
                    break;
                case 2:this.errorRegistoDono.setText("Email Inválido!");
                    this.errorRegistoDono.setVisible(true);
                    break;
                case 0:
                    TrocarMenu(3);
                    break;
                default:
                    throw new AssertionError();
        }
        }    
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Admin admin = new Admin("", "");
                new MenuAdmin(admin).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminsPanel;
    private javax.swing.JPanel DonosPanel;
    private javax.swing.JPanel UsersPanel;
    private javax.swing.JButton addAdmin;
    private javax.swing.JPanel addAdminPanel;
    private javax.swing.JButton addDono;
    private javax.swing.JPanel addDonoPanel;
    private javax.swing.JTable adminTable;
    private javax.swing.JButton deleteAdmin;
    private javax.swing.JButton deleteDono;
    private javax.swing.JButton deleteUser;
    private javax.swing.JTable donosTable;
    private javax.swing.JLabel errorRegistoAdmin;
    private javax.swing.JLabel errorRegistoDono;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField registo_email_input;
    private javax.swing.JTextField registo_nome_input;
    private javax.swing.JTextField registo_password_input;
    private javax.swing.JTextField registo_telemovel_input;
    private javax.swing.JTextField registoadmin_email_input;
    private javax.swing.JTextField registoadmin_password_input;
    private javax.swing.JTable usersTable;
    // End of variables declaration//GEN-END:variables

    
    private void initUsersTable(){
        ArrayList<Utilizador> users = d.getAllUsers();
        ArrayList<Utilizador> clientes = new ArrayList<>();
        
        for(Utilizador aux: users){
            if(aux instanceof Cliente){
                clientes.add(aux);
            }
        }
        
        DefaultTableModel  clientesTableModel = (DefaultTableModel) usersTable.getModel();
        clientesTableModel.setRowCount(0);
        for(int i = 0; i<clientes.size(); i++){
            clientesTableModel.addRow(new Object[]{
                clientes.get(i).getId(),
                clientes.get(i).getEmail(),
                clientes.get(i).getPassword(),
                clientes.get(i).getNome(),
                clientes.get(i).getnTelemovel(),
            });           
        }
    }
    
    
    private void initDonosTable(){
        ArrayList<Utilizador> users = d.getAllUsers();
        ArrayList<Utilizador> donos = new ArrayList<>();
        
        for(Utilizador aux: users){
            if(aux instanceof DonoStand){
                donos.add(aux);
            }
        }
        
        DefaultTableModel  donosTableModel = (DefaultTableModel) donosTable.getModel();
        donosTableModel.setRowCount(0);
        for(int i = 0; i<donos.size(); i++){
            donosTableModel.addRow(new Object[]{
                donos.get(i).getId(),
                donos.get(i).getEmail(),
                donos.get(i).getPassword(),
                donos.get(i).getNome(),
                donos.get(i).getnTelemovel(),
            });           
        }
    }
    
    private void initAdminTable(){
        ArrayList<Utilizador> users = d.getAllUsers();
        ArrayList<Utilizador> admins = new ArrayList<>();
        
        for(Utilizador aux: users){
            if(aux instanceof Admin){
                admins.add(aux);
            }
        }
        
        DefaultTableModel  adminTableModel = (DefaultTableModel) adminTable.getModel();
        adminTableModel.setRowCount(0);
        for(int i = 0; i<admins.size(); i++){
            adminTableModel.addRow(new Object[]{
                admins.get(i).getId(),
                admins.get(i).getEmail(),
                admins.get(i).getPassword(),
            });           
        }
    }
    
    
    private void TrocarMenu(int num){
        UsersPanel.setVisible(false);
        DonosPanel.setVisible(false);
        AdminsPanel.setVisible(false);
        addDonoPanel.setVisible(false);
        addAdminPanel.setVisible(false);
        
        errorRegistoDono.setVisible(false);
        errorRegistoAdmin.setVisible(false);
        
        switch(num) {
            case 1: UsersPanel.setVisible(true);initUsersTable(); break;
            case 2: DonosPanel.setVisible(true); initDonosTable(); break;
            case 3: AdminsPanel.setVisible(true); initAdminTable(); break;
            case 4: addDonoPanel.setVisible(true); break;
            case 5: addAdminPanel.setVisible(true); break;
            default: break;
        }
    }

}
